services:
    # Service pour le serveur web
    nginx:
        image: nginx:1.22-alpine
        restart: always
        container_name: nginx-monprof
        ports:
            - 8801:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./:/www/html/monprof
            - /etc/letsencrypt:/etc/letsencrypt
            - /etc/ssl/certs:/etc/ssl/certs
        depends_on:
            - php
    php:
        restart: always
        container_name: monprof-api
        build: .
        volumes:
            - ./:/www/html/monprof
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=194.163.141.34
            - DB_PORT=3306
            - DB_DATABASE=monprof_base_preprod
            - DB_USERNAME=richelieu
            - DB_PASSWORD=Azerty@123
        expose:
            - 9000
    adminer:
        image: adminer
        restart: always
        ports:
            - "8082:8080"
